/*
Gitea API.

This documentation describes the Gitea API.

API version: 1.20.0+dev-790-g61ad4c607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the EditIssueCommentOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditIssueCommentOption{}

// EditIssueCommentOption EditIssueCommentOption options for editing a comment
type EditIssueCommentOption struct {
	Body string `json:"body"`
}

// NewEditIssueCommentOption instantiates a new EditIssueCommentOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditIssueCommentOption(body string) *EditIssueCommentOption {
	this := EditIssueCommentOption{}
	this.Body = body
	return &this
}

// NewEditIssueCommentOptionWithDefaults instantiates a new EditIssueCommentOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditIssueCommentOptionWithDefaults() *EditIssueCommentOption {
	this := EditIssueCommentOption{}
	return &this
}

// GetBody returns the Body field value
func (o *EditIssueCommentOption) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *EditIssueCommentOption) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *EditIssueCommentOption) SetBody(v string) {
	o.Body = v
}

func (o EditIssueCommentOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditIssueCommentOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["body"] = o.Body
	return toSerialize, nil
}

type NullableEditIssueCommentOption struct {
	value *EditIssueCommentOption
	isSet bool
}

func (v NullableEditIssueCommentOption) Get() *EditIssueCommentOption {
	return v.value
}

func (v *NullableEditIssueCommentOption) Set(val *EditIssueCommentOption) {
	v.value = val
	v.isSet = true
}

func (v NullableEditIssueCommentOption) IsSet() bool {
	return v.isSet
}

func (v *NullableEditIssueCommentOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditIssueCommentOption(val *EditIssueCommentOption) *NullableEditIssueCommentOption {
	return &NullableEditIssueCommentOption{value: val, isSet: true}
}

func (v NullableEditIssueCommentOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditIssueCommentOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
