/*
Gitea API.

This documentation describes the Gitea API.

API version: 1.20.0+dev-790-g61ad4c607
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the PullRequestMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PullRequestMeta{}

// PullRequestMeta PullRequestMeta PR info if an issue is a PR
type PullRequestMeta struct {
	Merged   *bool      `json:"merged,omitempty"`
	MergedAt *time.Time `json:"merged_at,omitempty"`
}

// NewPullRequestMeta instantiates a new PullRequestMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPullRequestMeta() *PullRequestMeta {
	this := PullRequestMeta{}
	return &this
}

// NewPullRequestMetaWithDefaults instantiates a new PullRequestMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPullRequestMetaWithDefaults() *PullRequestMeta {
	this := PullRequestMeta{}
	return &this
}

// GetMerged returns the Merged field value if set, zero value otherwise.
func (o *PullRequestMeta) GetMerged() bool {
	if o == nil || IsNil(o.Merged) {
		var ret bool
		return ret
	}
	return *o.Merged
}

// GetMergedOk returns a tuple with the Merged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestMeta) GetMergedOk() (*bool, bool) {
	if o == nil || IsNil(o.Merged) {
		return nil, false
	}
	return o.Merged, true
}

// HasMerged returns a boolean if a field has been set.
func (o *PullRequestMeta) HasMerged() bool {
	if o != nil && !IsNil(o.Merged) {
		return true
	}

	return false
}

// SetMerged gets a reference to the given bool and assigns it to the Merged field.
func (o *PullRequestMeta) SetMerged(v bool) {
	o.Merged = &v
}

// GetMergedAt returns the MergedAt field value if set, zero value otherwise.
func (o *PullRequestMeta) GetMergedAt() time.Time {
	if o == nil || IsNil(o.MergedAt) {
		var ret time.Time
		return ret
	}
	return *o.MergedAt
}

// GetMergedAtOk returns a tuple with the MergedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PullRequestMeta) GetMergedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.MergedAt) {
		return nil, false
	}
	return o.MergedAt, true
}

// HasMergedAt returns a boolean if a field has been set.
func (o *PullRequestMeta) HasMergedAt() bool {
	if o != nil && !IsNil(o.MergedAt) {
		return true
	}

	return false
}

// SetMergedAt gets a reference to the given time.Time and assigns it to the MergedAt field.
func (o *PullRequestMeta) SetMergedAt(v time.Time) {
	o.MergedAt = &v
}

func (o PullRequestMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PullRequestMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Merged) {
		toSerialize["merged"] = o.Merged
	}
	if !IsNil(o.MergedAt) {
		toSerialize["merged_at"] = o.MergedAt
	}
	return toSerialize, nil
}

type NullablePullRequestMeta struct {
	value *PullRequestMeta
	isSet bool
}

func (v NullablePullRequestMeta) Get() *PullRequestMeta {
	return v.value
}

func (v *NullablePullRequestMeta) Set(val *PullRequestMeta) {
	v.value = val
	v.isSet = true
}

func (v NullablePullRequestMeta) IsSet() bool {
	return v.isSet
}

func (v *NullablePullRequestMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePullRequestMeta(val *PullRequestMeta) *NullablePullRequestMeta {
	return &NullablePullRequestMeta{value: val, isSet: true}
}

func (v NullablePullRequestMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePullRequestMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
